# Generated by Django 2.2.4 on 2020-04-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_category_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.category'),
            preserve_default=False,
        ),
    ]
