# Generated by Django 2.2.12 on 2020-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200427_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='TotalAmount',
            field=models.IntegerField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='number_of_slots',
            field=models.IntegerField(default=0, verbose_name='Number of Slots'),
        ),
    ]
