# Generated by Django 2.2.12 on 2020-04-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200427_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='total_slots',
            field=models.IntegerField(default=0, verbose_name='Total Fixed Slots'),
        ),
    ]
