# Generated by Django 2.2.12 on 2020-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_plan_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
