# Generated by Django 2.2.12 on 2020-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_subscription_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='linkWeb',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
