# Generated by Django 2.2.12 on 2020-04-28 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200428_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
